name: Cypress Tests

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Budapest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: |
          echo "First: ${{ github.event.inputs.FIRST }}"
          echo "Second: ${{ github.event.inputs.SECOND }}"
          echo "Third: ${{ github.event.inputs.THIRD }}"

      - name: Run Cypress Tests 
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_FIRST: ${{ github.event.inputs.FIRST }}
          CYPRESS_SECOND: ${{ github.event.inputs.SECOND }}
          CYPRESS_THIRD: ${{ github.event.inputs.THIRD }}

      #Artifacts
      - uses: actions/upload-artifact@v4
        name: Upload screenshots in case of always
        if: always()
        with:
          name: cypress-screenshots
          path: cypress

      - uses: actions/upload-artifact@v4
        name: Upload videos in case of always
        if: always()
        with:
          name: cypress-videos
          path: cypress
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: cucumber-report.html
